### PR TITLE
Update endpoint

### PR DESCRIPTION
**Pull request by imnutz**

### CODE REVIEW

**Review by kietdo360 — APPROVED** [review]
LGTM

**Comment by tung-vu-td** [comment]
@imnutz  Need to remove this too: https://github.com/treasure-data/td-unity-sdk-package#use-server-side-upload-timestamp

**Review by tung-vu-td — APPROVED** [review]
LGTM

**Review by nmpennypacker — APPROVED** [review]
Reviewed for data exfiltrations

**Pull request merged**
